"use client"

import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Sparkles, TrendingUp, Droplets, Zap, AlertCircle, RefreshCw } from "lucide-react";
import { mockZones } from "@/lib/mock-data";
import { weeklyIrrigationSummary, WeeklyIrrigationSummaryOutput } from "@/ai/flows/weekly-irrigation-summary";
import { Skeleton } from "@/components/ui/skeleton";

export default function AnalyticsPage() {
  const [report, setReport] = useState<WeeklyIrrigationSummaryOutput | null>(null);
  const [loading, setLoading] = useState(true);

  async function generateReport() {
    setLoading(true);
    try {
      const input = {
        weekNumber: 42,
        year: 2024,
        reportDate: new Date().toISOString().split('T')[0],
        zoneSummaries: mockZones.map(z => ({
          zoneId: z.id,
          plantType: z.description.split('.')[0] || "Garden Plant",
          avgSoilMoisturePercentage: z.soilMoisture,
          minSoilMoisturePercentage: Math.max(0, z.soilMoisture - 10),
          maxSoilMoisturePercentage: Math.min(100, z.soilMoisture + 15),
          avgTemperatureCelsius: z.temperature,
          totalWateringEvents: z.status === 'Watering' ? 14 : 7,
          totalWaterConsumedLiters: Math.floor(Math.random() * 400) + 150,
          totalWateringDurationMinutes: Math.floor(Math.random() * 180) + 45,
          dominantWateringMode: z.type,
          peakWateringDay: "Tuesday",
          significantEvents: z.status === 'Warning' ? ["Sensor discrepancy detected"] : []
        }))
      };

      const result = await weeklyIrrigationSummary(input);
      setReport(result);
    } catch (error) {
      console.error("Failed to generate analytics report:", error);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    generateReport();
  }, []);

  return (
    <div className="space-y-8 pb-20">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="font-headline text-3xl font-bold tracking-tight text-primary">System Analytics</h1>
          <p className="text-muted-foreground font-body mt-1">AI-driven insights and performance reporting.</p>
        </div>
        <Button 
          onClick={generateReport} 
          disabled={loading}
          variant="outline" 
          className="gap-2"
        >
          <RefreshCw className={`size-4 ${loading ? 'animate-spin' : ''}`} />
          Refresh Analysis
        </Button>
      </div>

      {loading ? (
        <div className="grid gap-6">
          <Card className="border-none shadow-sm bg-card">
            <CardHeader>
              <Skeleton className="h-6 w-1/4 mb-2" />
              <Skeleton className="h-4 w-1/2" />
            </CardHeader>
            <CardContent className="space-y-4">
              <Skeleton className="h-24 w-full" />
              <div className="grid md:grid-cols-2 gap-4">
                <Skeleton className="h-32 w-full" />
                <Skeleton className="h-32 w-full" />
              </div>
            </CardContent>
          </Card>
        </div>
      ) : report ? (
        <div className="space-y-6">
          {/* Overall Summary */}
          <Card className="border-none shadow-sm bg-primary/5 border border-primary/10 overflow-hidden relative">
            <div className="absolute top-0 right-0 p-6">
              <Sparkles className="size-8 text-primary opacity-20" />
            </div>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-foreground">
                <TrendingUp className="size-5 text-primary" />
                Weekly Performance Review
              </CardTitle>
              <CardDescription>Executive summary generated by HydroSense AI.</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-lg leading-relaxed text-foreground/90 font-medium">
                {report.overallSummary}
              </p>
            </CardContent>
          </Card>

          <div className="grid gap-6 md:grid-cols-2">
            {/* Zone Summaries */}
            <div className="space-y-6">
              <h2 className="text-xl font-bold px-1 flex items-center gap-2 text-foreground">
                <Droplets className="size-5 text-primary" />
                Zone Breakdown
              </h2>
              {report.zoneSummaries.map((zs) => (
                <Card key={zs.zoneId} className="border-none shadow-sm bg-card hover:ring-1 hover:ring-primary/10 transition-all">
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base font-bold text-primary">
                      {mockZones.find(z => z.id === zs.zoneId)?.name || zs.zoneId}
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      {zs.summary}
                    </p>
                  </CardContent>
                </Card>
              ))}
            </div>

            {/* Recommendations */}
            <div className="space-y-6">
              <h2 className="text-xl font-bold px-1 flex items-center gap-2 text-foreground">
                <Zap className="size-5 text-amber-500" />
                Actionable Recommendations
              </h2>
              <div className="grid gap-4">
                {report.recommendations.map((rec, idx) => (
                  <Card key={idx} className="border-l-4 border-l-primary border-none shadow-sm bg-card">
                    <CardContent className="p-4 flex gap-3">
                      <div className="mt-1">
                        <Badge variant="outline" className="rounded-full px-2 py-0 border-primary/30 text-primary">#{idx + 1}</Badge>
                      </div>
                      <p className="text-sm font-medium text-foreground/90">{rec}</p>
                    </CardContent>
                  </Card>
                ))}
              </div>

              {/* System Anomalies */}
              <Card className="bg-destructive/5 border-destructive/10 shadow-none border">
                <CardHeader className="pb-2">
                   <CardTitle className="text-sm font-bold flex items-center gap-2 text-destructive">
                      <AlertCircle className="size-4" />
                      Maintenance Alerts
                   </CardTitle>
                </CardHeader>
                <CardContent>
                   <p className="text-xs text-muted-foreground leading-relaxed">
                     Anomalies detected in Zone 3 moisture tracking. The system recommends checking the soil sensor calibration or looking for irrigation leaks.
                   </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      ) : (
        <div className="text-center py-20 bg-card rounded-xl border border-dashed">
          <p className="text-muted-foreground">No analysis data available. Try refreshing the report.</p>
        </div>
      )}
    </div>
  );
}